### PR TITLE
[GUI][Bug] Fix "Select all" / "Unselect all" logic in coincontrol

### LINKED ISSUE #1592: [Bug] Select all button in Coin Control isn't working properly
Go to `Send` tab -> `Coin Control` -> select any of the UTXOs manually -> click `Select all` button:

selectAll1

After clicking `Select all`, result will be as following (which is that no UTXOs are selected):

selectAll2

After clicking `Select all` **again**, result will be as following:

selectAll3

1) Shouldn't it be more logical if user manually select an UTXO(s), that `Select all` button changes to `Unselect all`, so then everything works as intended?

2) Or after clicking `Select all` button that all UTXOs actually get selected

### PR DESCRIPTION
**Pull request by random-zebra**
Prioritize the action described by the button:
- if "Select All", then verify that all entries are checked, otherwise check them
- if "Unselect All", then verify that all entries are unchecked, otherwise uncheck them.

Closes #1592 

**Note**: if we had just prioritized `Qt::Unchecked` at the beginning, instead of `Qt::Checked`, without taking into account the status/text of the button, we would have solved 1592, but we'd have another bug where, using first "Select All" to check all entries, and then manually deselecting some entry, results in a successive "Unselect All" still behaving like "Select All".

### CODE REVIEW

File: src/qt/coincontroldialog.cpp [hunk 1]
```diff
@@ -225,10 +225,12 @@ void CoinControlDialog::setModel(WalletModel* model)
 // (un)select all
 void CoinControlDialog::buttonSelectAllClicked()
 {
-    Qt::CheckState state = Qt::Checked;
+    // "Select all": if some entry is unchecked, then check it
+    // "Unselect all": if some entry is checked, then uncheck it
+    Qt::CheckState state = ui->pushButtonSelectAll->text() == tr("Select all") ? Qt::Unchecked : Qt::Checked;
```
Comment (furszy) [inline src/qt/coincontroldialog.cpp:230]: would be good to use a boolean here, hardcoded texts are not good for statements.

**Comment by random-zebra** [comment]
Added a boolean variable `fSelectAllToggled` to remove the dependency on the `pushButtonSelectAll` button's text, as suggested by @furszy
