### PR TITLE
[Bug] Updated stakeable coins in staker thread

### LINKED ISSUE #1923: [Bug] TX gets marked as conflicted - 2 scenarios outlined
### Describe the issue
An issue with a TX being marked as Conflicted.

#### If so, please list the steps to reproduce below
Scenario 1:
1. Create a new TX.
2. Stake the next block.
3. TX is then conflicted.

Scenario 2:
1. Stake a block.
2. Wallet will attempt to stake the same input previously staked.

### Expected behavior
Should not attempt to stake recent/or previous input. 

### Actual behavior
After adding more log prints to the code to investigate what was going on, I found that the wallet is trying to stake the most recent input. So when a new TX is produced and you stake the next block, it's always marked as conflicted. What's happening is that it's trying to stake one of the inputs used in the previously generated TX. The same issue is seen while generating new stake. The wallet will attempt to stake several times the previous input that has already been staked.

### What version of PIVX Core are you using?
Linux 64 bit v4.3.0

### Machine specs:
Linux 18.04

### PR DESCRIPTION
**Pull request by random-zebra**
Currently, during the staking thread, the list of available coins is updated every 5 minutes.
This can lead to two problems:
- If a coin is not included due to low confirmations number, when it matures, it cannot be staked immediately: it gets included only after the full 5 minutes.
- If a coin is spent, it is not removed immediately from the list. So, if a valid kernel is found with said coin, the following two things happen.
First, the newly created block fails `TestBlockValidity` (as it contains essentially a double spend) and gets discarded by the staker, who also clears his mempool (thus removing the transaction that was spending the coin). 
Then, after few seconds, the staker tries again with the same coin, finding again a valid kernel with it, but this time creating a (valid) empty block. The wallet transaction, originally spending the stake input, and later removed from the memory pool, is now marked conflicted.

For now, let's address the issue by:
- reloading the list of available coins whenever the tip hash changes (so, at least, at every block).
- checking for in-wallet spent-status before staking (as the list of coins is updated only when a new block arrives, a certain coin could have been spent in the mempool afterwards).

Closes #1923 

A better approach (future work), would be to implement an interface in the miner, subscribing to the wallet signals and updating the stakeable coins cache only when a coin is added, or is spent (or matures).

### CODE REVIEW

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -2938,26 +2938,29 @@ bool CWallet::CreateCoinStake(
...
         if (IsSpent(outPoint)) {
+            // remove it from the available coins
+            it = availableCoins->erase(it);
             continue;
         }
 
         // This should never happen
         if (stakeInput.IsZPIV()) {
             LogPrintf("%s: ERROR - zPOS is disabled\n", __func__);
+            it++;
```
Comment (furszy) [inline src/wallet/wallet.cpp:2963]: we can remove this check, the stake input is created at the beginning of the loop, `IsZPIV()` is always false.

**Review by furszy — APPROVED** [review]
nice fix man, ACK 056cf79ae3bfc43481a891d848a2cabdf78a9976.
Left one minor comment that noticed reviewing the PR, doesn't need to be included here.

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (random-zebra) [reply src/wallet/wallet.cpp:2963]: Out of scope here, but sure.

Comment (furszy) [reply src/wallet/wallet.cpp:2963]: yep, wrote it on the main comment. No need to include it here.

**Review by Fuzzbawls — APPROVED** [review]
utACK 056cf79ae3bfc43481a891d848a2cabdf78a9976
