### PR TITLE
[RPC][Bug] Fix masternodecurrent: return next winner, not rank-1 mn

### LINKED ISSUE #1348: [RPC] masternodecurrent != getmasternodewinners
### Describe the issue 
'masternodecurrent' returns the first mn from list, but this is not the actual current winner. 

### Can you reliably reproduce the issue?
1. getblockcount
2. masternodecurrent
3. getmasternodewinners
4. listmasternodes

### Expected behavior
Should masternodecurrent not return the winner instead of the mn on rank 1?

### What version of PIVX Core are you using?
v4.0.2, v2.3 tested

```
09:08:37
getblockcount

09:08:37
2217343


09:08:41
getmasternodewinners

09:08:41
[
  {
    "nHeight": 2217343,
    "winner": {
      "address": "D5CmbndCXiBUdjyV67oEvkKMd12nf3XRmv",
      "nVotes": 10
    }
  },
]


09:08:44
masternodecurrent

09:08:44
{
  "protocol": 70918,
  "txhash": "460be84bb8e881a242c3c251f49705471d3a1a5e35c9f37781ecf7c8cf2a39f8",
  "pubkey": "DPTUe1AXFe4TGPwkWsVfk6iUZmekQ7suoN",
  "lastseen": 1582275712,
  "activeseconds": 3953846
}


09:10:12
listmasternodes

09:10:12
[
  {
    "rank": 1,
    "network": "ipv4",
    "txhash": "460be84bb8e881a242c3c251f49705471d3a1a5e35c9f37781ecf7c8cf2a39f8",
    "outidx": 1,
    "pubkey": "04b85bf9fc5123db77afdc8bf2f812835f7cf44cbea64c5786f9352ac68712736d14ea0b72bab682fde242bd950f3089f705fe4b35e5a02cae5a4761f8833cb369",
    "status": "ENABLED",
    "addr": "DPTUe1AXFe4TGPwkWsVfk6iUZmekQ7suoN",
    "version": 70918,
    "lastseen": 1582275712,
    "activetime": 3953846,
    "lastpaid": 1582167351
  },
]
```
https://explorer.pivx.link/block/8428984bf10fed26cdac6b172bb0c609f463a220e6f4eb0d7b08e3980df96510

### PR DESCRIPTION
**Pull request by random-zebra**
`masternodecurrent` RPC is improperly returning the masternode with rank 1 instead of the next winner.
Closes #1348 

```
> getblockcount
2236241

> masternodecurrent
{
  "protocol": 70918,
  "txhash": "cfa69f018741e0960a436788391d9d2cec0f9aceed30e883a78818f7c073fba1",
  "pubkey": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
  "lastseen": 1583439177,
  "activeseconds": 6690804
}

> getmasternodewinners 0
[
  {
    "nHeight": 2236242,
    "winner": {
      "address": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
      "nVotes": 10
    }
  },
  ...
]
```
<https://explorer.pivx.link/block/9fe33eedf5f61a8e9f8d50b9007c25d1b0260f0c97f88265feda4c06dfa86725>

Note: `GetCurrentMasterNode` returns the masternode with lower rank and it's used as winner only when no valid block payee can be found. We should probably change its name to something more meaningful (`GetLowestRankMasterNode` ?) and change the comment calling it "winner". Same goes for the comment above `CMasternode::CalculateScore` (masternodes are not even paid based on their scores, but only on the time of their last payment).

### CODE REVIEW

File: src/rpc/masternode.cpp [hunk 1]
```diff
@@ -198,24 +198,30 @@ UniValue masternodecurrent (const UniValue& params, bool fHelp)
...
             "}\n"
 
             "\nExamples:\n" +
             HelpExampleCli("masternodecurrent", "") + HelpExampleRpc("masternodecurrent", ""));
 
-    CMasternode* winner = mnodeman.GetCurrentMasterNode(1);
+    int nHeight = 0;
+    {
+        LOCK(cs_main);
+        nHeight = chainActive.Height() + 1;
```
Comment (furszy) [inline src/rpc/masternode.cpp]: Do it prettier:

```
nHeight = WITH_LOCK(cs_main, return chainActive.Height() + 1);
```
