### PR TITLE
[GUI][Bug] Reset custom change address

### LINKED ISSUE #1526: [Bug] Unable to return Change Address to default
After setting up Change Address for the first time, it is impossible to delete the address, leave it blank and click Save, so that it returns to Default. It returns `Invalid change address`.

warning2

warning3

### PR DESCRIPTION
**Pull request by random-zebra**
First commit fixes a bug where the `btnChangeAddress` in SendWidget was deactivated, despite a custom address still being saved (e.g. saving a valid address, and then trying to change it to an invalid one).

Second commit addresses a feature request: being able to reset only the change address (without resetting the whole coin control) directly from within the dialog.
With this PR, when a custom change address is set, the text of the "CANCEL" button in `SendChangeAddressDialog` is changed to "RESET" and, when clicked, resets the default change address to CNoDestination (which means that a new change address will be created during the send operation).
The upright "X" button retains its original function of just closing the dialog.
Closes #1526

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
I think we should take an extra precaution with regards to an invalid address being entered by resetting the change address. this will prevent a previously saved (valid) change address from persisting.

```diff
Index: src/qt/pivx/send.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/qt/pivx/send.cpp	(revision 4763c2c08d2f80b96027eda4ab4c2a7642d14e08)
+++ src/qt/pivx/send.cpp	(date 1587713628926)
@@ -601,6 +601,7 @@
                 ui->btnChangeAddress->setActive(true);
             } else {
                 inform(tr("Invalid change address"));
+                QMetaObject::invokeMethod(dialog, "reset", Qt::DirectConnection);
             }
         }
     }

```

**Comment by random-zebra** [comment]
Added a commit to move the address validation inside SendChangeAddressDialog.
The reason is twofold: first, it addresses the concern raised by @Fuzzbawls about a previously (valid) address being persisted when entering an invalid one. Second, it offers better UX, removing the need for an extra click, in case of errors during copy-paste.

File: src/qt/pivx/sendchangeaddressdialog.cpp [hunk 1]
```diff
@@ -70,6 +72,25 @@ void SendChangeAddressDialog::reset()
     close();
 }
 
-SendChangeAddressDialog::~SendChangeAddressDialog(){
+void SendChangeAddressDialog::save()
+{
+    // validate address
+    if (!walletModel->validateAddress(ui->lineEditAddress->text())) {
+        inform(tr("Invalid change address"));
```
Comment (furszy) [inline src/qt/pivx/sendchangeaddressdialog.cpp:79]: Would just put "Invalid address", the user is already in the change address dialog which has only a single edit box.

Comment (random-zebra) [reply src/qt/pivx/sendchangeaddressdialog.cpp:79]: done.

**Comment by random-zebra** [comment]
Error message changed to "Invalid address" / squashed into last commit.

File: src/qt/pivx/sendchangeaddressdialog.cpp [hunk 2]
```diff
@@ -8,10 +8,15 @@
...
 #include "qt/pivx/qtutils.h"
 
-SendChangeAddressDialog::SendChangeAddressDialog(QWidget *parent) :
+SendChangeAddressDialog::SendChangeAddressDialog(QWidget* parent, WalletModel* model) :
     QDialog(parent),
+    walletModel(model),
     ui(new Ui::SendChangeAddressDialog)
 {
+    if (!walletModel) {
+        LogPrintf("%s: ERROR: No wallet model set.\n", __func__);
```
Comment (furszy) [inline src/qt/pivx/sendchangeaddressdialog.cpp:17]: Two things about this: 

In QT we are not using `LogPrintf`, we are using `qDebug`.
`qDebug() << __func__ << ": No wallet model set.";`

And, if we really want to have this check, would rather throw a runtime exception. Constructors initialize objects or not, there is no half done initialization. Create a widget in an invalid state, because of a bad argument, without notifying the caller, shouldn't never happen.

Comment (random-zebra) [reply src/qt/pivx/sendchangeaddressdialog.cpp]: Yes. Makes sense to throw. Fixed.
