### PR TITLE
[Wallet] Combine fees when possible and fix autocombine insufficient funds

### LINKED ISSUE #496: Autocombine gives 'Insuficient funds' errors
Pretty much what the title says.
When autocombinerewards is on, the transactions are more often than not failing with an `Insuficient funds` error message.
See #488 for discovery of the bug.
This issue is for tracking purpose. @Mrs-X is currently investigating the problem.

### PR DESCRIPTION
**Pull request by Warrows**
This is firstly to fix #496. Ensuring autocombine stops failing with `Insufficient funds` error messages. (Thanks to @Mrs-X for the help)
It also ensure that when a change address is provided in coin control the change is going to this address in an already existing output.
Last, it gives autocombine transactions the address being combined as a change address. Thus lowering TX size and avoiding generating new change addresses when trying to reduce UTXO fragmentation.

### CODE REVIEW

File: src/wallet.cpp [hunk 1]
```diff
@@ -2713,11 +2713,25 @@ bool CWallet::CreateTransaction(const vector<pair<CScript, CAmount> >& vecSend,
                     // TODO: pass in scriptChange instead of reservekey so
                     // change transaction isn't always pay-to-pivx-address
                     CScript scriptChange;
+                    bool combineChange = false;
 
                     // coin control: send change to custom address
-                    if (coinControl && !boost::get<CNoDestination>(&coinControl->destChange))
+                    if (coinControl && !boost::get<CNoDestination>(&coinControl->destChange)){
```
Comment (Fuzzbawls) [inline src/wallet.cpp]: Nit: need a space between the closing `)` of the conditional and the opening bracket `{`

File: src/wallet.cpp [hunk 2]
```diff
@@ -2713,11 +2713,25 @@ bool CWallet::CreateTransaction(const vector<pair<CScript, CAmount> >& vecSend,
...
                         scriptChange = GetScriptForDestination(coinControl->destChange);
 
+                        vector<CTxOut>::iterator it = txNew.vout.begin();
+                        for(; it != txNew.vout.end();){
```
Comment (Fuzzbawls) [inline src/wallet.cpp]: Nit: need a space between the closing `)` of the conditional and the opening bracket `{` 
Also a space between `for` and the opening `(` of the conditional.

File: src/wallet.cpp [hunk 3]
```diff
@@ -2736,18 +2750,20 @@ bool CWallet::CreateTransaction(const vector<pair<CScript, CAmount> >& vecSend,
...
-                    // add the dust to the fee.
-                    if (newTxOut.IsDust(::minRelayTxFee)) {
-                        nFeeRet += nChange;
-                        nChange = 0;
-                        reservekey.ReturnKey();
-                    } else {
-                        // Insert change txn at random position:
-                        vector<CTxOut>::iterator position = txNew.vout.begin() + GetRandInt(txNew.vout.size() + 1);
-                        txNew.vout.insert(position, newTxOut);
+                    if (!combineChange){
```
Comment (Fuzzbawls) [inline src/wallet.cpp]: Nit: need a space between the closing `)` of the conditional and the opening bracket `{`

**Comment by Warrows** [comment]
And it's done. Pretty impressive OCD you got there ;) I should start using .clang-format to avoid your nits in the future.

**Comment by s3v3nh4cks** [comment]
utACK

File: src/wallet.cpp [hunk 4]
```diff
@@ -2713,11 +2713,25 @@ bool CWallet::CreateTransaction(const vector<pair<CScript, CAmount> >& vecSend,
...
                     CScript scriptChange;
+                    bool combineChange = false;
 
                     // coin control: send change to custom address
-                    if (coinControl && !boost::get<CNoDestination>(&coinControl->destChange))
+                    if (coinControl && !boost::get<CNoDestination>(&coinControl->destChange)) {
                         scriptChange = GetScriptForDestination(coinControl->destChange);
 
+                        vector<CTxOut>::iterator it = txNew.vout.begin();
+                        for (; it != txNew.vout.end();) {
```
Comment (presstab) [inline src/wallet.cpp]: Why not use `while` here?

File: src/wallet.cpp [hunk 5]
```diff
@@ -4034,16 +4052,22 @@ void CWallet::AutoCombineDust()
...
         CReserveKey keyChange(this); // this change address does not end up being used, because change is returned with coin control switch
         string strErr;
         CAmount nFeeRet = 0;
 
-        //get the fee amount
-        CWalletTx wtxdummy;
-        CreateTransaction(vecSend, wtxdummy, keyChange, nFeeRet, strErr, coinControl, ALL_COINS, false, CAmount(0));
-        vecSend[0].second = nTotalRewardsValue - nFeeRet - 500;
+        // 10% safety margin to avoid "Insufficient funds" errors
+        vecSend[0].second = nTotalRewardsValue - (nTotalRewardsValue / 10);
```
Comment (presstab) [inline src/wallet.cpp]: So this sets the fee to 10% of the transaction value? Not sure that this will work in all situations, such as when 10% of a very small value would be below the minimum tx fee. Maybe we should grab the serialized size of the tx and calculate fee per byte, then add a small safety net on top?

Comment (Mrs-X) [reply src/wallet.cpp]: No, it reduces the transaction value(!) by 10%, not the fee. And with the reduced 10% the insufficient funds error does not happen.

However, @Warrows removed the `CreateTransaction(vecSend, wtxdummy, keyChange, nFeeRet, strErr, coinControl, ALL_COINS, false, CAmount(0));` call which computes the fees with a dummy transaction before the actual transaction is created.
As it is now it's always created with `nFeeRet == 0`, I don't think that's correct.

I think a better way would be:
```
CAmount nFeeRet = 0;
//get the fee amount
CWalletTx wtxdummy;

// 10% safety margin to avoid "Insufficient funds" errors
vecSend[0].second = nTotalRewardsValue - (nTotalRewardsValue / 10);

// Compute fees
CreateTransaction(vecSend, wtxdummy, keyChange, nFeeRet, strErr, coinControl, ALL_COINS, false, CAmount(0));

// Subtract fees if possible
if(nTotalRewardsValue >= nFeeRet)
    vecSend[0].second = nTotalRewardsValue - nFeeRet;

if (!CreateTransaction(vecSend, wtx, keyChange, nFeeRet, strErr, coinControl, ALL_COINS, false, CAmount(0))) {
...
```

Comment (Warrows) [reply src/wallet.cpp]: Actually, the input value is unchanged, but the redeemed value is reduced by 10%.
It could be seen as 10% fees. But in fact one of the changes is to collect the value not needed for fees and put it back in the output. 

As pointed out by @Mrs-X  I also removed the evaluation of fees and send a transaction requiring 0 fee. This result in the `createTransaction()` function taking the minimal fee, up to 10% of the input. But as I said what is unused is returned. 

So the fees are actually left to the `createTransaction()` function to choose, as designed. It's now only called once.

One of the changes introduced in #497 consist in not sending transactions when the value is below the threshold and the fee not 0. So low value txs with fees above 10% should not be a concern.

**Comment by Mrs-X** [comment]
Just for my understanding, you always add the change to an existing output, and because you never create a new output you don't have to care about dust...

**Comment by Warrows** [comment]
That's it. But I am doing so only if coincontrol is used and one of the output addresses is also the same as an input address. 
This I believe is a corner case only happening with autocombine (and maybe multisend?). I believe Bitcoin discourages the reuse of an address. But for us it's the very point of autocombine to group UTXOs inside a unique address.

File: src/wallet.cpp (hunk 4 above)
Comment (Warrows) [reply src/wallet.cpp]: Absolutely no reason, good catch.

**Comment by Mrs-X** [comment]
Tested and (almost) does what it says, so ACK from my side.

**1:** normal transactions without a custom change address still work 👍 

**2:** actual test:
Setup: 3 inputs with 5, 10 and 15 = 30 PIV
Sent: 29 PIV

Coin-Control estimation before send:
```
Inputs   : 30.00
Spend    : 29.00
Fee      :  0.03116412
After Fee: 29.96883588
Change   :  0.96883588
```

Logged transaction (this is where the change gets added to the existing output):
```
Change: 1.00000000
  Change added, old value: 29.00000000
  Change added, new value: 30.00000000
Change: 0.97098513
  Change added, old value: 29.00000000
  Change added, new value: 29.97098513
Change: 0.97092543
  Change added, old value: 29.00000000
  Change added, new value: 29.97092543
```
Sent transaction (obviously the last computation was used):
```
Total debit: -29.97092543
Transaction fee: -0.02907457
```

**3:** little Nit: it doesn't care whether I select the coins via Coin-Control or automatically, when the rest of the prerequisites are fulfilled it adds the change to the existing output. That's the only issue I found, but from my point of view you can leave it like that.

If @presstab is fine with your changes I'll merge it.

**Comment by Mrs-X** [comment]
I decided that presstab's fine with your changes 😄 and will merge it...
