### PR TITLE
[GUI][Bug] Fix language selection invalidly stored

### LINKED ISSUE #1597: [Bug] Translations aren't showing although language is 100% translated
After 1590 merge, language change isn't working although language is translated 100%. I restarted the wallet multiple times, I tested even with fresh wallet creation, it isn't working.

translationsBug1

OS: Ubuntu 18.04 LTS

**EDIT:** It isn't working on Windows 10 as well, latest master branch.

### PR DESCRIPTION
**Pull request by furszy**
Quick solution to the translations issue #1597 .

fixes #1597

### CODE REVIEW

File: src/qt/pivx/settings/settingsdisplayoptionswidget.cpp [hunk 1]
```diff
@@ -144,7 +144,7 @@ void SettingsDisplayOptionsWidget::onResetClicked()
 void SettingsDisplayOptionsWidget::setMapper(QDataWidgetMapper *mapper)
 {
     mapper->addMapping(ui->comboBoxDigits, OptionsModel::Digits);
-    mapper->addMapping(ui->comboBoxLanguage, OptionsModel::Language);
+    mapper->addMapping(ui->comboBoxLanguage, OptionsModel::Language, "currentData");
```
Comment (random-zebra) [inline src/qt/pivx/settings/settingsdisplayoptionswidget.cpp:147]: This seems to prevent the comboBox from automatically selecting the used language (after restart or after initial welcome screen) but at least fixes the issue at hand. So, can be fixed in a successive PR.
