### PR TITLE
[Bug] Simpler nTimeSmart computation

### LINKED ISSUE #1346: [GUI] Transaction date issue
### Describe the issue
Sending a transaction showed on the Transactions page with the wrong date.

### Can you reliably reproduce the issue?
I have not tried

### Expected behavior
Correct date should be shown

### Actual behavior
Incorrect date is shown on the windows Qt Wallet; but not an Ubuntu Qt Wallet

### Additional details
The problem seems to be related to the transaction timestamp:
Block Explorer:
```
  "time": 1581386295,
  "blocktime": 1581386295
```
Ubuntu `gettransaction`:
```
  "blocktime": 1581386295,
  "time": 1581386293,
  "timereceived": 1581386293,
```
Windows `gettransaction`:
```
  "blocktime": 1581386295,
  "time": 1578904590,
  "timereceived": 1581386284,
```

Note the time difference in the Windows `gettransaction` vs. the timereceived; so likely the root of the issue is somewhere in `CWallet::ComputeTimeSmart()`

### What version of PIVX Core are you using?
4.0.2

### Machine specs:
- OS: Windows 7

### PR DESCRIPTION
**Pull request by random-zebra**
Given the strict timestamp checks enforced with POS TimeProtocol v2 (introduced with #1002: a block cannot have a timestamp earlier than previous blocks and cannot be more than 15 seconds in the future), we don't need the complex (and error-prone) logic of the current implementation of `ComputeTimeSmart`. 
We can, instead, simply rely on the blocktime, which already ensures a proper ordering for the transactions.
This also allows us to encapsulate the function in the `CWalletTx` class (renaming it to `UpdateTimeSmart`).

We can also get rid of the additional `GetComputedTxTime` (with its additional LOCK, and main chain lookup), and just use `GetTxTime`.

Finally, update the nSmartTime when a mempool transaction is added to a block.

This should, hopefully, fix #1346 (further testing needed).

### CODE REVIEW

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -1177,16 +1178,22 @@ int64_t CWalletTx::GetTxTime() const
...
-    LOCK(cs_main);
-    if (ContainsZerocoins()) {
-        if (IsInMainChain())
-            return mapBlockIndex.at(hashBlock)->GetBlockTime();
-        else
-            return nTimeReceived;
+    nTimeSmart = nTimeReceived;
+    if (!hashBlock.IsNull()) {
+        if (mapBlockIndex.count(hashBlock)) {
+            nTimeSmart = mapBlockIndex[hashBlock]->GetBlockTime();
```
Comment (Fuzzbawls) [inline src/wallet/wallet.cpp:1193]: lets not use the `[]` operator here and use `mapBlockIndex.at(hashBlock)->GetBlockTime();` instead. Even though this is guarded by the above `if` check, probably best to stick to never using the `[]` operator when reading from a map. (https://github.com/PIVX-Project/PIVX/blob/master/doc/developer-notes.md#c-data-structures)

Comment (random-zebra) [reply src/wallet/wallet.cpp]: Yes, even though this line was already like this in the previous `ComputeTimeSmart` (and, as you pointed out, makes no difference, given the `if` check), it makes sense to fix it here, for consistency.
Updated.

**Comment by furszy** [comment]
Concept ACK and code looking great 👌 .
